import NewEvent from "@/components/form/new-event";
import { Balloon } from "lucide-react";
import { Metadata } from "next";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Crear Evento - Eventia",
  description: "Generated by create next app",
};

export default function CreateEvent() {
  return (
    <div>
      <h1 className="text-4xl font-bold leading-tight">
        <span className="inline">
          ¡Creá y Publicá tu propio Evento!
          <Balloon className="inline-block w-10 h-10 ml-2 align-middle" />
        </span>
      </h1>
      <p className="text-stone-700">
        Nosotros nos encargamos de que tenga éxito.
      </p>
      <Suspense>
        <NewEvent />
      </Suspense>
    </div>
  );
}
